### ISSUE TITLE
نحوه استفاده از کتاب خانه

### ISSUE THREAD

**Issue by amir200xven** [emamirazavi/jldate#1]
با سلام

امکانش هست نحوه استفاده و چند مثال عملی از کتاب خانه فوق بدهید ؟ 

 امکان استفاده از کتاب خانه فوق با 
fullcalendar

هست

**Comment by emamirazavi** [comment]
سلام، با عرض پوزش به خاطر تاخیر زیاد. من فعلا به علت وقت کم یک ایمیل براتون
میفرستم. اگر ممکنه شما راهنماش رو اضافه کنید. اگر هم نتونستید باهاشون کار
کنید بگید تا بیشتر توضیح بدهم. لطفا ایمیلتون رو به emamirazavi@gmail.com
بفرستید. ضمنا در اولین فرصت فایلای مثالی خواهم گذاشت. من این پروژه اول با
فول کلندر ۳ راه اندازی کردم پس به احتمال زیاد نباید تو راه اندازی به مشکل
بخورید.  موفق باشید.

**Comment by amir200xven** [comment]
سلام، دوست عزیز ایمیل رو خدمت شما ارسال کردم، بی صبرانه منتظر خبر از جانب شما هستم
